site_name: CHBH-on-BEAR
site_url: https://ajquinn.github.io/chbh-on-bear/

repo_name: CHBH-on-BEAR
repo_url: https://github.com/AJQuinn/chbh-on-bear
edit_uri: blob/main/docs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

theme:
  name: material
  features:
    - content.code.copy
  logo: CHBH_logo.jpg

nav:
  - Home: index.md
  - Getting Started on Bear: bear.md
  - R: R/R.md
  - Python:
    - MNE-Python : mne/mne.md
    - TensorFlow : mne/mne.md
  - MatLab: matlab/matlab.md
  - FSL: fsl/fsl.md
  - Containers: containers/containers.md
