site_name: CHBH-on-Bear
site_url: https://example.com/
nav:
    - Home: index.md
    - Getting Started on Bear: bear.md
    - R: R/R.md
    - Python:
        - MNE-Python : mne/mne.md
        - TensorFlow : mne/mne.md
    - MatLab: matlab/matlab.md
    - FSL: fsl/fsl.md

