site_name: CHBH-on-BEAR
site_url: https://ajquinn.github.io/chbh-on-bear/

repo_name: CHBH-on-BEAR
repo_url: https://github.com/AJQuinn/chbh-on-bear
edit_uri: blob/main/docs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

theme:
  name: material
  features:
    - content.code.copy
  logo: CHBH_logo.jpg

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Software Index: neuroimaging_software.md
  - R: R/R.md
  - Python:
    - Python: python/python.md
    - MNE-Python : python/mne.md
    - OSL: python/osl.md
    - Conda: python/conda.md
  - MatLab:
    - MatLab: matlab/matlab.md
    - FieldTrip: matlab/fieldtrip.md
    - SPM: matlab/spm.md
    - EEGLab: matlab/eeglab.md
  - FSL: fsl/fsl.md
  - FreeSurfer: freesurfer/freesurfer.md
  - Containers: containers/containers.md
  - FAQs: faqs.md
